export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'

export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS'

export const USER_LOGIN_SUCCESS ='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILD = 'USER_LOGIN_FAILD'
export const USER_LOGOUT = 'USER_LOGOUT'