export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'

export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS'

export const USER_LOGIN_SUCCESS ='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILD = 'USER_LOGIN_FAILD'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED'